# Generated by Django 5.0.6 on 2024-06-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending')], max_length=20),
        ),
    ]
